#!/bin/sh

# am335x-evm Build Environment Setup Script
#
# Normally this is called as '. ./am335x-init-build-env'
#
# This works in most shells (not dash), but not all of them pass the arguments
# when being sourced.  To workaround the shell limitation use "set <builddir>"
# prior to sourcing this script.
#
if [ -n "$BASH_SOURCE" ]; then
    THIS_SCRIPT=$BASH_SOURCE
elif [ -n "$ZSH_NAME" ]; then
    THIS_SCRIPT=$0
else
    THIS_SCRIPT="$(pwd)/am335x-init-build-env"
    if [ ! -e "$THIS_SCRIPT" ]; then
        echo "Error: $THIS_SCRIPT doesn't exist!" >&2
        echo "Please run this script in am335x-init-build-env's directory." >&2
        exit 1
    fi
fi
if [ -n "$BBSERVER" ]; then
    unset BBSERVER
fi

if [ -z "$ZSH_NAME" ] && [ "$0" = "$THIS_SCRIPT" ]; then
    echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'" >&2
    exit 1
fi

if [ -z "$BEAGLEROOT" ]; then
    BEAGLEROOT=$(dirname "$THIS_SCRIPT")
    BEAGLEROOT=$(readlink -f "$BEAGLEROOT")
fi
unset THIS_SCRIPT

if [ ! -e "$BEAGLEROOT/build" ]; then
    echo "$BEAGLEROOT/build doesn't exist!" >&2
    echo "Creating $BEAGLEROOT/build now." >&2
    mkdir $BEAGLEROOT/build
fi

TEMPLATECONF="$BEAGLEROOT/meta-beagle/conf"

export TEMPLATECONF
export BEAGLEROOT

cd "$BEAGLEROOT/poky"

.  oe-init-build-env "$BEAGLEROOT/build/am335x-evm"
